version: '3.8'

services:
  bot:
    build: .
    container_name: movie-bot
    env_file: .env
    depends_on:
      - db
    restart: on-failure
    command: python main.py

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  db-init:
    image: mysql:8.0
    container_name: mysql-init
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./movies_database.sql:/docker-entrypoint-initdb.d/init.sql:ro
    entrypoint: [ "bash", "-c", "sleep 20 && echo 'Initializing DB...'" ]
    restart: "no"

volumes:
  db_data:
