GENRE_TRANSLATIONS = {
    "Drama":      {"en": "Drama",      "ru": "Драма",         "de": "Drama"},
    "Comedy":     {"en": "Comedy",     "ru": "Комедия",       "de": "Komödie"},
    "Thriller":   {"en": "Thriller",   "ru": "Триллер",       "de": "Thriller"},
    "Music":      {"en": "Music",      "ru": "Музыка",        "de": "Musik"},
    "Action":     {"en": "Action",     "ru": "Боевик",        "de": "Action"},
    "Adventure":  {"en": "Adventure",  "ru": "Приключения",   "de": "Abenteuer"},
    "Family":     {"en": "Family",     "ru": "Семейный",      "de": "Familie"},
    "Romance":    {"en": "Romance",    "ru": "Романтика",     "de": "Romantik"},
    "Documentary":{"en": "Documentary","ru": "Документальный","de": "Dokumentation"},
    "Mystery":    {"en": "Mystery",    "ru": "Мистика",       "de": "Mystery"},
    "Sci-Fi":     {"en": "Sci-Fi",     "ru": "Фантастика",    "de": "Science-Fiction"},
    "Biography":  {"en": "Biography",  "ru": "Биография",     "de": "Biografie"},
    "Horror":     {"en": "Horror",     "ru": "Ужасы",         "de": "Horror"},
    "Fantasy":    {"en": "Fantasy",    "ru": "Фэнтези",       "de": "Fantasy"},
    "Animation":  {"en": "Animation",  "ru": "Мультфильм",    "de": "Animation"},
    "Crime":      {"en": "Crime",      "ru": "Криминал",      "de": "Krimi"},
    "Sport":      {"en": "Sport",      "ru": "Спорт",         "de": "Sport"},
    "War":        {"en": "War",        "ru": "Военный",       "de": "Krieg"},
    "Short":      {"en": "Short",      "ru": "Короткометражка","de": "Kurzfilm"},
    "History":    {"en": "History",    "ru": "История",       "de": "Geschichte"},
    "News":       {"en": "News",       "ru": "Новости",       "de": "Nachrichten"},
    "Western":    {"en": "Western",    "ru": "Вестерн",       "de": "Western"},
    "Musical":    {"en": "Musical",    "ru": "Мюзикл",        "de": "Musical"},
}
